services:
  app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
      - db-init

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  db-init:
    build:
      context: ./db-init
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
